# Generated by Django 5.0.6 on 2024-06-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='server_settings')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('about_us', models.URLField(blank=True, null=True)),
                ('privacy', models.URLField(blank=True, null=True)),
                ('terms', models.URLField(blank=True, null=True)),
                ('hide_campaign_leadform', models.BooleanField(default=False)),
                ('hide_client_leadform', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
            ],
        ),
    ]
