# Generated by Django 5.0.6 on 2024-07-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serversetting',
            old_name='logo',
            new_name='logo_login',
        ),
        migrations.AddField(
            model_name='serversetting',
            name='logo_main',
            field=models.ImageField(blank=True, null=True, upload_to='server_settings'),
        ),
    ]
