# Generated by Django 5.0.6 on 2024-07-01 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_logo_serversetting_logo_login_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('dialer_nick', models.CharField(blank=True, max_length=50, null=True)),
                ('hiring_date', models.DateField(blank=True, null=True)),
                ('camp', models.CharField(blank=True, max_length=30, null=True)),
                ('login_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('upl', 'UPL'), ('annual', 'Annual'), ('casual', 'Casual'), ('sick', 'Sick'), ('inactive', 'Inactive'), ('dropped', 'Dropped'), ('blacklisted', 'Blacklisted')], default='active', max_length=20, null=True)),
                ('dialer_user', models.CharField(blank=True, max_length=40, null=True)),
                ('dialer_password', models.CharField(blank=True, max_length=40, null=True)),
                ('hourly_rate', models.FloatField(blank=True, null=True)),
                ('daily_rate', models.FloatField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('residence', models.CharField(blank=True, max_length=50, null=True)),
                ('discord', models.CharField(blank=True, max_length=100, null=True)),
                ('payoneer', models.CharField(blank=True, max_length=100, null=True)),
                ('instapay', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_role', to='core.role')),
            ],
        ),
    ]
