# Generated by Django 5.0.6 on 2024-07-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_role_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='camp',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
