# Generated by Django 5.0.6 on 2024-07-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_username_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='server_settings'),
        ),
        migrations.AddField(
            model_name='serversetting',
            name='logo_dashboard_dims',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
