# Generated by Django 5.0.6 on 2024-07-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_serversetting_favicon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serversetting',
            old_name='logo_dashboard_dims',
            new_name='logo_dashboard_height',
        ),
        migrations.AddField(
            model_name='serversetting',
            name='logo_dashboard_width',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
