# Generated by Django 5.0.6 on 2024-07-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_logo_dashboard_dims_serversetting_logo_dashboard_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='settings_theme',
            field=models.BooleanField(default=True),
        ),
    ]
