# Generated by Django 5.0.6 on 2024-07-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_settings_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='settings_theme',
            field=models.CharField(choices=[('white', 'White'), ('dark', 'Dark')], default='white', max_length=50),
        ),
    ]
