# Generated by Django 5.0.6 on 2024-07-03 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profile_settings_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, choices=[('cold_caller', 'Cold Caller'), ('acq_manager', 'Acquisition Manager'), ('dispo_manager', 'Disposition Manager'), ('data_manager', 'Data Manager')], max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(blank=True, choices=[('highschool', 'High School'), ('undergraduate', 'Undergradute'), ('bachelors', 'Bachelors'), ('mba', 'MBA')], max_length=50, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('start_date', models.TextField(blank=True, null=True)),
                ('voice_record', models.TextField(blank=True, max_length=50, null=True)),
                ('shift', models.CharField(blank=True, choices=[('part_time', 'Part Time'), ('full_time', 'Full Time')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
