# Generated by Django 5.0.6 on 2024-07-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='applications_audio/'),
        ),
    ]
