# Generated by Django 4.1 on 2024-07-03 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_application_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 7, 3, 22, 12, 31, 401726, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.CharField(blank=True, choices=[('cold_caller', 'Cold Caller'), ('acq_manager', 'Acquisition Manager'), ('dispo_manager', 'Disposition Manager'), ('data_manager', 'Data Manager'), ('Sales', 'Sales')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 3, 22, 12, 43, 811517, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
