# Generated by Django 4.1 on 2024-07-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_application_date_alter_application_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='voice_record',
        ),
        migrations.AlterField(
            model_name='application',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='applications_audio'),
        ),
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.CharField(blank=True, choices=[('cold_caller', 'Cold Caller'), ('acq_manager', 'Acquisition Manager'), ('dispo_manager', 'Disposition Manager'), ('data_manager', 'Data Manager'), ('sales', 'Sales')], max_length=50, null=True),
        ),
    ]
