# Generated by Django 5.0.6 on 2024-07-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_method',
            field=models.CharField(choices=[('payoneer', 'Payoneer'), ('instapay', 'InstaPay')], default='payoneer', max_length=50),
        ),
    ]
