# Generated by Django 5.0.6 on 2024-07-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='maps_theme',
            field=models.CharField(choices=[('white', 'White'), ('dark', 'Dark')], default='white', max_length=50),
        ),
    ]
