# Generated by Django 5.0.6 on 2024-07-11 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profile_maps_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DialerListSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('hold', 'Hold'), ('pending', 'Pending'), ('inactive', 'Inactive')], max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignDispo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp_dispo', to='core.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='DialerList',
            fields=[
                ('start_time', models.TimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('contacts', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('skip_tracing', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_campaign', to='core.campaign')),
                ('dialer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dialer')),
            ],
        ),
        migrations.CreateModel(
            name='DialerListPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('dialer_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dialerlist')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('pushed_time', models.TimeField(blank=True, null=True)),
                ('pushed_date', models.DateField(blank=True, null=True)),
                ('lead_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('agent_name', models.CharField(blank=True, max_length=50, null=True)),
                ('agent_user', models.CharField(blank=True, max_length=50, null=True)),
                ('dialer_nick', models.CharField(blank=True, max_length=50, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('house', 'House'), ('vacant_land', 'Vacant Land'), ('business', 'Business'), ('apartment', 'Apartment'), ('codo', 'Condo'), ('mobile_home', 'Mobile Home')], default='house', max_length=50, null=True)),
                ('lead_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('callback', 'Callback'), ('duplicate', 'Duplicate'), ('invaild', 'Invalid')], default='pending', max_length=50, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=50, null=True)),
                ('seller_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('seller_email', models.CharField(blank=True, max_length=50, null=True)),
                ('timeline', models.CharField(blank=True, choices=[('two_weeks', '2 Weeks'), ('one_month', '1 Month'), ('two_month', '2 Month'), ('three_month', '3 Month'), ('four_month', '4 Month'), ('five_month', '5 Month'), ('six_month', '6 Month'), ('more_than_six_month', '+6 Month')], default='two_weeks', max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('property_address', models.TextField(blank=True, null=True)),
                ('asking_price', models.CharField(blank=True, max_length=50, null=True)),
                ('market_value', models.CharField(blank=True, max_length=50, null=True)),
                ('general_info', models.TextField(blank=True, null=True)),
                ('zillow_url', models.TextField(blank=True, null=True)),
                ('callback', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_notes', models.TextField(blank=True, null=True)),
                ('quality_notes', models.TextField(blank=True, null=True)),
                ('quality_to_agent_notes', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_campaign', to='core.campaign')),
                ('dialer_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_list', to='core.dialerlist')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handled_by_lead_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
