# Generated by Django 5.0.6 on 2024-07-11 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_dialer_dialerlistsource_campaign_campaigndispo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialerlistperformance',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_camp', to='core.dialerlist'),
        ),
        migrations.AddField(
            model_name='dialerlistperformance',
            name='dispo_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='dialerlistperformance',
            name='dialer_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_list', to='core.dialerlist'),
        ),
        migrations.CreateModel(
            name='CampaignDispoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp_dispo', to='core.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='dialerlistperformance',
            name='dispo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_dispos', to='core.campaigndisposetting'),
        ),
        migrations.DeleteModel(
            name='CampaignDispo',
        ),
    ]
