# Generated by Django 5.0.6 on 2024-07-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_dialerlistperformance_campaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='daily_rate',
            new_name='monthly_salary',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='dialer_nick',
            new_name='phone_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('hourly', 'Hourly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
    ]
