# Generated by Django 5.0.6 on 2024-07-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_team_rename_daily_rate_profile_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='national_id',
            field=models.ImageField(blank=True, null=True, upload_to='national_ids/'),
        ),
    ]
