# Generated by Django 5.0.6 on 2024-07-17 20:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_id',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.random_name_national_id),
        ),
    ]
