# Generated by Django 5.0.6 on 2024-07-23 15:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_team_team_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acq_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='coldcalling_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='data_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='discovery_method',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('batchservice', 'Batchservice'), ('linkedin', 'Linkedin'), ('upwork', 'Upwork or other freelancing sites'), ('google_search', 'Google Search'), ('google_ads', 'Google Ads'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('referral', 'Referral from a Friend'), ('email_newsletter', 'Email Newsletter'), ('outreach_call', 'Outreach Representative Calls')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dispo_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='joining_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='leadmanager_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.random_name_profile_pic),
        ),
    ]
