# Generated by Django 5.0.6 on 2024-07-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_profile_residence_alter_profile_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('hold', 'Hold'), ('pending', 'Pending'), ('inactive', 'Inactive')], max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='services',
            field=models.ManyToManyField(related_name='client_services', to='core.service'),
        ),
    ]
