# Generated by Django 5.0.6 on 2024-07-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_service_active_alter_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='acq_service',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coldcalling_service',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='data_service',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dispo_service',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='leadmanager_service',
        ),
    ]
