# Generated by Django 5.0.6 on 2024-07-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_profile_acq_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agents_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
