# Generated by Django 5.0.6 on 2024-07-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_profile_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='client_services', to='core.service'),
        ),
    ]
