# Generated by Django 5.0.6 on 2024-07-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_dialerlist_contactlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialer',
            name='dialer_type',
            field=models.CharField(blank=True, choices=[('calling', 'Calling'), ('texting', 'Texting')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
