# Generated by Django 5.0.6 on 2024-07-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_dialer_dialer_type_alter_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('source_type', models.CharField(blank=True, choices=[('pulling', 'List Pulling'), ('skip_tracing', 'Skip Tracing'), ('skip_pull', 'List Pulling & Skip Tracing')], max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ListSource',
        ),
    ]
