# Generated by Django 5.0.6 on 2024-07-25 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_datasource_delete_listsource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='description',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='first_call_time',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='last_call_time',
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(blank=True, choices=[('calling', 'Calling Service'), ('texting', 'Texting Service'), ('email', 'Email Service'), ('admin', 'Admin Service'), ('marketing', 'Marketing Service'), ('sales', 'Sales Service')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='datasources',
            field=models.ManyToManyField(blank=True, related_name='datasources_campaign', to='core.datasource'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='lead_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CampaignCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('campaign', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
                ('dialer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dialer')),
            ],
        ),
        migrations.CreateModel(
            name='DataSourceCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('campaign', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
                ('datasource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.datasource')),
            ],
        ),
    ]
